In [0]:
# Signifcance of RNN: For modeling sequential data.


In [0]:
 import numpy as np
 

In [0]:
time_stamps = 100 # number of positions in the sentence 
input_features = 32 # number of features in each position
output_features = 64 # number of outputs for each input feature

In [0]:
input_t = np.random.random((time_stamps,input_features))

In [29]:
print(inputs)

[[0.53205669 0.87796622 0.5944579  ... 0.4563593  0.79313558 0.10388875]
 [0.86525105 0.26738344 0.14528559 ... 0.33658205 0.18014802 0.30309926]
 [0.33890636 0.90180636 0.18545465 ... 0.08512261 0.21376094 0.23897839]
 ...
 [0.11160196 0.97640981 0.28166183 ... 0.40318425 0.57177154 0.84894023]
 [0.74820364 0.87083804 0.82701447 ... 0.58968486 0.79513299 0.09325774]
 [0.85685976 0.73517881 0.84701215 ... 0.23651329 0.49953364 0.08646357]]


In [30]:
print(inputs.shape)

(100, 32)


In [31]:
state_t = np.zeros((output_features))
print(state_t)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
# Intialize weights randomly 

In [0]:
W = np.random.random((output_features,input_features))
U = np.random.random((output_features,output_features))
b = np.random.random((output_features, ))

In [0]:
# Lets implement RNN

In [0]:
success_output = []
for input_t in inputs:
  output_t = np.tanh(np.dot(W, input_t) + np.dot(U,state_t)+b)
  success_output.append(output_t)
  state_t = output_t 

In [0]:
final_output_seq = np.concatenate(success_output,axis=0)

In [35]:
print(final_output_seq)

[0.99999833 0.99999843 0.99999994 ... 1.         1.         1.        ]


In [38]:
print(final_output_seq.shape)

(6400,)
